## Diccionario de datos

Hay cinco tablas en el conjunto de datos, y tendrás que usarlas todas para hacer el preprocesamiento de datos y el análisis exploratorio de datos. A continuación se muestra un diccionario de datos que enumera las columnas de cada tabla y describe los datos que contienen.

- `instacart_orders.csv`: cada fila corresponde a un pedido en la aplicación Instacart.
    - `'order_id'`: número de ID que identifica de manera única cada pedido.
    - `'user_id'`: número de ID que identifica de manera única la cuenta de cada cliente.
    - `'order_number'`: el número de veces que este cliente ha hecho un pedido.
    - `'order_dow'`: día de la semana en que se hizo el pedido (0 si es domingo).
    - `'order_hour_of_day'`: hora del día en que se hizo el pedido.
    - `'days_since_prior_order'`: número de días transcurridos desde que este cliente hizo su pedido anterior.
- `products.csv`: cada fila corresponde a un producto único que pueden comprar los clientes.
    - `'product_id'`: número ID que identifica de manera única cada producto.
    - `'product_name'`: nombre del producto.
    - `'aisle_id'`: número ID que identifica de manera única cada categoría de pasillo de víveres.
    - `'department_id'`: número ID que identifica de manera única cada departamento de víveres.
- `order_products.csv`: cada fila corresponde a un artículo pedido en un pedido.
    - `'order_id'`: número de ID que identifica de manera única cada pedido.
    - `'product_id'`: número ID que identifica de manera única cada producto.
    - `'add_to_cart_order'`: el orden secuencial en el que se añadió cada artículo en el carrito.
    - `'reordered'`: 0 si el cliente nunca ha pedido este producto antes, 1 si lo ha pedido.
- `aisles.csv`
    - `'aisle_id'`: número ID que identifica de manera única cada categoría de pasillo de víveres.
    - `'aisle'`: nombre del pasillo.
- `departments.csv`
    - `'department_id'`: número ID que identifica de manera única cada departamento de víveres.
    - `'department'`: nombre del departamento.

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
# 1. Cargar los datos

ordenes = pd.read_csv('./datos/instacart_orders.csv', sep=';')

In [8]:
# 2. Ver los datos
# 2.1 Estructura (esquema)

ordenes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 478967 entries, 0 to 478966
Data columns (total 6 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_id                478967 non-null  int64
 1   user_id                 478967 non-null  int64
 2   order_number            478967 non-null  int64
 3   order_dow               478967 non-null  int64
 4   order_hour_of_day       478967 non-null  int64
 5   days_since_prior_order  450148 non-null  float64
dtypes: float64(1), int64(5)
memory usage: 21.9 MB

In [9]:
# 2.2 Ver las filas

ordenes.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,1515936,183418,11,6,13,30.0
1,1690866,163593,5,5,12,9.0
2,1454967,39980,4,5,19,2.0
3,1768857,82516,56,0,20,10.0
4,3007858,196724,2,4,12,17.0

In [10]:
ordenes.tail()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
478962,3210681,5617,5,1,14,7.0
478963,3270802,112087,2,3,13,6.0
478964,885349,82944,16,2,11,6.0
478965,216274,4391,3,3,8,8.0
478966,2071924,1730,18,1,14,15.0

In [ ]:
# Muestreo:
# No probabilistico: head, tail
# Probabilistico: 
#  1. Simple: todas las filas tienen la misma posibilidad de ser seleccionadas
#  2. Estratificado: se selecciona un porcentaje de un estrato (grupo)
#  3. Pesado: se selecciona basado en un peso

In [12]:
ordenes.sample(10)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
246496,1991506,42254,23,5,14,8.0
376455,2481779,9910,75,5,19,2.0
197567,1016381,116213,6,1,7,5.0
331915,3257749,188414,34,6,23,6.0
252282,527156,54729,10,1,7,7.0
275491,2794345,102722,35,6,15,4.0
349500,2080287,111598,17,1,10,4.0
305655,2654024,183760,2,6,15,1.0
30650,2464579,134460,6,0,15,21.0
114059,1907335,7045,34,0,8,3.0

In [ ]:
# Calidad de los datos
# Faltantes/Nulos/NA -> Completitud
# Valores 'raros' -> Consistencia en valor
# Duplicados -> Precision
# Consistencia en los tipos de datos, nombres de las colmnas -> Consistencia en forma

In [23]:
# Completitud

columnas_con_valores_faltantes = ordenes.isna().sum()

In [25]:
columnas_con_valores_faltantes = columnas_con_valores_faltantes.reset_index()

In [18]:
ordenes.shape

(478967, 6)

In [27]:
columnas_con_valores_faltantes.columns = ['nombre_columna', 'qty_ausentes']

In [28]:
columnas_con_valores_faltantes

           nombre_columna  qty_ausentes
0                order_id             0
1                 user_id             0
2            order_number             0
3               order_dow             0
4       order_hour_of_day             0
5  days_since_prior_order         28819

In [29]:
columnas_con_valores_faltantes['rate_ausentes'] = (columnas_con_valores_faltantes['qty_ausentes'] * 100) / ordenes.shape[0]

In [30]:
columnas_con_valores_faltantes

           nombre_columna  qty_ausentes  rate_ausentes
0                order_id             0       0.000000
1                 user_id             0       0.000000
2            order_number             0       0.000000
3               order_dow             0       0.000000
4       order_hour_of_day             0       0.000000
5  days_since_prior_order         28819       6.016907

In [31]:
type(columnas_con_valores_faltantes)

pandas.core.frame.DataFrame

In [ ]:
# Eliminar: NUNCA ES LA PRIMERA OPCION
# -> Fila: % filas no representan un valor significativo
# -> Columna > 50% de valores faltanes

# Rellenar: PRIMERA OPCION
# -> Valores de tendencia central: media, mediana, moda -> ALTERA LA DISTRIBUCION DE LOS DATOS
# -> Valores especificos: ES NECESARIO UN CRITERIO -1, 0
# -> IA/ML para un rellenado inteligente

# EL PORQUE FALTAN:
# MNAR -> MISSING NOT AT RANDOM (HAY UN PATRON)
# MAR -> MISSING AT RANDOM
# MCAR -> MISSING COMPLETLY AT RANDOM (SEGUROS 100% DE QUE LOS QUE FALTAN SON ALEATOREOS)

In [32]:
ordenes[ordenes['days_since_prior_order'].isna()]

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
28,133707,182261,1,3,10,NaN
96,787445,25685,1,6,18,NaN
100,294410,111449,1,0,19,NaN
103,2869915,123958,1,4,16,NaN
104,2521921,42286,1,3,18,NaN
...,...,...,...,...,...,...
478895,2589657,205028,1,0,16,NaN
478896,2222353,141211,1,2,13,NaN
478922,2272807,204154,1,1,15,NaN
478926,2499542,68810,1,4,19,NaN
478945,1387033,22496,1,5,14,NaN

In [33]:
# De un analisis inicial, 10 filas de ordenes primerizas tienen la columna dias desde la orden previa como vacio

In [35]:
ordenes_con_valores_faltantes = ordenes.query('days_since_prior_order.isna()')

In [36]:
ordenes_con_valores_faltantes

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
28,133707,182261,1,3,10,NaN
96,787445,25685,1,6,18,NaN
100,294410,111449,1,0,19,NaN
103,2869915,123958,1,4,16,NaN
104,2521921,42286,1,3,18,NaN
...,...,...,...,...,...,...
478895,2589657,205028,1,0,16,NaN
478896,2222353,141211,1,2,13,NaN
478922,2272807,204154,1,1,15,NaN
478926,2499542,68810,1,4,19,NaN
478945,1387033,22496,1,5,14,NaN

In [37]:
ordenes_con_valores_faltantes['order_number'].unique()

array([1])

In [ ]:
# TODAS las ordenes que tienen days_since_prior_order vacio provienen de la primera compra de cada usuario!